package com.shocktrade.javascript.app.model

import scala.scalajs.js

/**
 * Detailed Quote
 * @author lawrence.daniels@gmail.com
 */
case class DetailedQuote(symbol: String,
                         name: String,
                         assetType: String,
                         legalType: String,
                         var riskLevel: String,
                         high52Week: Double, low52Week: Double, change52Week: Double,
                         movingAverage50Day: Double, movingAverage200Day: Double,
                         change52WeekSNP500: Double, beta: Double,
                         revenue: Double,
                         revenuePerShare: Double,
                         revenueGrowthQuarterly: Double,
                         grossProfit: Double,
                         EBITDA: Double,
                         netIncomeAvailToCommon: Double,
                         dilutedEPS: Double,
                         earningsGrowthQuarterly: Double,
                         totalCash: Double,
                         totalDebt: Double,
                         currentRatio: Double,
                         totalCashPerShare: Double,
                         totalDebtOverEquity: Double,
                         bookValuePerShare: Double,
                         returnOnAssets: Double,
                         profitMargin: Double,
                         mostRecentQuarterDate: Double,
                         returnOnEquity: Double,
                         operatingMargin: Double,
                         fiscalYearEndDate: Double,
                         enterpriseValue: Double,
                         trailingPE: Double,
                         forwardPE: Double,
                         pegRatio: Double,
                         priceOverSales: Double,
                         priceOverBookValue: Double,
                         enterpriseValueOverRevenue: Double,
                         enterpriseValueOverEBITDA: Double,
                         operatingCashFlow: Double,
                         leveredFreeCashFlow: Double,
                         avgVolume3Month: Double,
                         avgVolume10Day: Double,
                         sharesOutstanding: Double,
                         sharesFloat: Double,
                         pctHeldByInsiders: Double,
                         pctHeldByInstitutions: Double,
                         sharesShort: Double,
                         shortRatio: Double,
                         shortPctOfFloat: Double,
                         sharesShortPriorMonth: Double,
                         forwardAnnualDividendRate: Double,
                         forwardAnnualDividendYield: Double,
                         trailingAnnualDividendYield: Double,
                         divYield5YearAvg: Double, payoutRatio: Double,
                         dividendDate: Double, exDividendDate: Double, lastSplitFactor: Double, lastSplitDate: Double,
                         products: js.Array[js.Any],
                         active: Boolean)