IF OBJECT_ID('dbo.key_statistics', 'U') IS NOT NULL
  DROP TABLE dbo.key_statistics;

CREATE TABLE dbo.key_statistics (
  key_statistics_id           INTEGER PRIMARY KEY IDENTITY (1, 1),
  securities_id               INTEGER NOT NULL,
  lowLimit                    DECIMAL(12, 5),
  highLimit                   DECIMAL(12, 2),
  OATSReportable              BIT,
  OTCStatus                   VARCHAR(32),
  avgVol3m                    BIGINT,
  avgVolume                   BIGINT,
  avgVolume10Day              BIGINT,
  avgVolume3Month             BIGINT,
  beta                        DECIMAL(12, 5),
  bookValuePerShare           DECIMAL(12, 5),
  changePct                   DECIMAL(12, 5),
  change52Week                DECIMAL(12, 5),
  change52WeekHigh            VARCHAR(32),
  change52WeekLow             VARCHAR(32),
  change52WeekSNP500          DECIMAL(12, 5),
  currentRatio                DECIMAL(12, 5),
  dilutedEPS                  DECIMAL(12, 5),
  divShare                    DECIMAL(12, 5),
  divYield                    DECIMAL(12, 5),
  dividend                    DECIMAL(12, 5),
  dividendDate                DATETIME,
  dividendPayDate             DATETIME,
  dividendYield5YearAvg       DECIMAL(12, 5),
  exDividendDate              DATETIME,
  earningsGrowthQuarterly     DECIMAL(12, 5),
  enterpriseValue             DECIMAL(12, 5),
  enterpriseValueOverEBITDA   DECIMAL(12, 5),
  enterpriseValueOverRevenue  DECIMAL(12, 5),
  eps                         DECIMAL(12, 5),
  epsEstCurrentYear           DECIMAL(12, 5),
  epsEstNextQtr               DECIMAL(12, 5),
  epsEstNextYear              DECIMAL(12, 5),
  expirationTime              DATETIME,
  fiscalYearEndDate           DATETIME,
  floatShares                 BIGINT,
  forwardAnnualDividendRate   VARCHAR(32),
  forwardAnnualDividendYield  VARCHAR(32),
  forwardPE                   DECIMAL(12, 5),
  grossProfit                 DECIMAL(12, 2),
  holdings                    DECIMAL(12, 2),
  holdingsGain                DECIMAL(12, 2),
  ipoYear                     INTEGER,
  lastSplitDate               DATETIME,
  lastSplitFactor             DECIMAL(12, 5),
  leveredFreeCashFlow         DECIMAL(12, 5),
  marketCapIntraday           DECIMAL(12, 5),
  marketCategory              VARCHAR(32),
  mostRecentQuarterDate       DATETIME,
  movingAverage200Day         DECIMAL(12, 5),
  movingAverage50Day          DECIMAL(12, 5),
  netIncomeAvailToCommon      DECIMAL(12, 5),
  notes                       TEXT,
  summaryQuote                TEXT,
  businessSummary             TEXT,
  operatingCashFlow           DECIMAL(12, 5),
  operatingMargin             VARCHAR(32),
  otcDailyLastUpdated         DATETIME,
  payoutRatio                 DECIMAL(12, 2),
  pctHeldByInsiders           DECIMAL(12, 2),
  pctHeldByInstitutions       DECIMAL(12, 2),
  peRatio                     DECIMAL(12, 2),
  pegRatio                    DECIMAL(12, 2),
  pegRatio5YearExp            VARCHAR(32),
  priceOverBookValue          DECIMAL(12, 5),
  priceOverSales              DECIMAL(12, 5),
  profitMargin                DECIMAL(12, 5),
  returnOnAssets              DECIMAL(12, 5),
  returnOnEquity              DECIMAL(12, 2),
  revenue                     DECIMAL(12, 2),
  revenueGrowthQuarterly      DECIMAL(12, 2),
  revenuePerShare             DECIMAL(12, 5),
  sharesFloat                 BIGINT,
  sharesOutstanding           BIGINT,
  sharesOwned                 BIGINT,
  sharesShort                 BIGINT,
  sharesShortPriorMonth       BIGINT,
  shortPctOfFloat             DECIMAL(12, 2),
  shortRatio                  DECIMAL(12, 5),
  target1Y                    DECIMAL(12, 5),
  totalCash                   DECIMAL(12, 5),
  totalCashPerShare           DECIMAL(12, 5),
  totalDebt                   DECIMAL(12, 5),
  totalDebtOverEquity         DECIMAL(12, 2),
  trailingAnnualDividendYield DECIMAL(12, 2),
  trailingPE                  DECIMAL(12, 2),
  unitOfTrade                 INTEGER,
  EBITDA                      DECIMAL(12, 2),
  target1Yr                   DECIMAL(12, 5),
  nextEarningsDate            DATETIME,
  creationTime                DATETIME NOT NULL DEFAULT getdate(),
  lastUpdatedTime             DATETIME
)

--CREATE UNIQUE INDEX dbo.key_statistics_xpk ON dbo.key_statistics ( symbol, exchange )